version: "3.9"

services:
  backend:
    build: .
    container_name: onlineshop_backend
    restart: always
    ports:
      - "5001:5000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: onlineshop
    depends_on:
      - mysql
    networks:
      - onlineshop_net

  mysql:
    image: mysql:8.0
    container_name: onlineshop_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: onlineshop
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - onlineshop_net

networks:
  onlineshop_net:

volumes:
  db_data:
